spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dressmaker01
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      generate-statistics: true      

server:
  port: 8080
  



      